### ISSUE TITLE
Quesion) pytorch version 

### ISSUE THREAD

**Issue by intlabSeJun** [xiaoye-hhh/SAAI#2]
Thank you for contribution, good work!!

Is it okay for training? as follows:
- gpu 3090
- cuda 11.3
- pytorch==1.12.1
- torchvision==0.13.1

It says 22G is needed for training, but I only use 9G in my environment, so I ask if there is a problem.

Thanks. Have a nice day.

**Comment by xiaoye-hhh** [comment]
It should be no problem. The training will take approximately two hours.
