### ISSUE TITLE
请问应该在哪里设置显卡

### ISSUE THREAD

**Issue by MengWH** [xiaoye-hhh/SAAI#3]
![308a7f56a40d74bd15a87849949b107](https://github.com/xiaoye-hhh/SAAI/assets/48003067/4bf14dd0-056f-4ac8-959f-622f69ee9924)
貌似显卡这边会报错
请问应该在哪里设置具体用哪张显卡

**Comment by xiaoye-hhh** [comment]
您好，我的机器只有一张卡就没有写。如果有多张卡，可以利用下面代码指定空闲的卡：
```python
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0" 
```
我这边没有多卡测试，如果没问题的话欢迎提交pr。

**Comment by MengWH** [comment]
非常感谢您的工作，目前问题已经解决。我上面报错的情况貌似是因为下面这段代码，torch.float16改成True就不报错了：
![5a2826dd23a6145b15745d3bf8546fc](https://github.com/xiaoye-hhh/SAAI/assets/48003067/146062db-7864-42bf-bb3a-56ef2c75c8a3)
