### ISSUE TITLE
ablation study复现结果不匹配

### ISSUE THREAD

**Issue by ddwwbb2001** [xiaoye-hhh/SAAI#7]
作者大大你好，我在复现你的ablation study部分的时候，仅使用id_loss，去掉pdloss和csloss，baseline+safl在sysu数据集在all-search and single-shot mode的setting下测出的rank1:61.44；map:56.68，和paper里的rank1: 75.03、map: 71.69不太相符，请问还有什么训练细节需要注意吗或者是我忽略了什么setting的细节吗？文章里提到的baseline：ResNet-50 with horizontal part features和saai模型使用的backbone是相同的吗？

**Comment by xiaoye-hhh** [comment]
75.03和71.69是单去掉AIM的结果，主要是测试一下AIM这个模块的作用。

**Comment by ddwwbb2001** [comment]
我对比了一下我的训练log和你给出的log，发现你给出的log里面多了一个split_num，请问这个参数的作用是什么？
[Uploading SYSU_p7_dp_l2_seed_0.txt…]()

**Comment by ddwwbb2001** [comment]
我对比了一下我的训练log和你给出的log，发现你给出的log里面多了一个split_num，请问这个参数的作用是什么？这是我训练的log文件
[SYSU_p7_dp_l2_seed_0.txt](https://github.com/xiaoye-hhh/SAAI/files/14731302/SYSU_p7_dp_l2_seed_0.txt)

**Comment by ddwwbb2001** [comment]
> 我对比了一下我的训练log和你给出的log，发现你给出的log里面多了一个split_num，请问这个参数的作用是什么？这是我训练的log文件 [SYSU_p7_dp_l2_seed_0.txt](https://github.com/xiaoye-hhh/SAAI/files/14731302/SYSU_p7_dp_l2_seed_0.txt)

[log.txt](https://github.com/xiaoye-hhh/SAAI/files/14731553/log.txt)
这是你之前上传的log文件

**Comment by ddwwbb2001** [comment]
> 我对比了一下我的训练log和你给出的log，发现你给出的log里面多了一个split_num，请问这个参数的作用是什么？这是我训练的log文件 [SYSU_p7_dp_l2_seed_0.txt](https://github.com/xiaoye-hhh/SAAI/files/14731302/SYSU_p7_dp_l2_seed_0.txt)

这是你之前上传到log文件，参数里面有一个split_num，我在saai的配置文件里面没有找到
[log.txt](https://github.com/xiaoye-hhh/SAAI/files/14731557/log.txt)

**Comment by xiaoye-hhh** [comment]
那个没什么影响，你有修改什么其它参数吗？

**Comment by xiaoye-hhh** [comment]
那个没什么影响，结果的差异可能要检查一下实验环境。
